// Privacy Policy content generated by Termly — March 23, 2026
// TODO: Fill in blanks: contact email, cookie notice URL, mailing address
export const privacyHtml = `
<style>
  [data-custom-class='body'], [data-custom-class='body'] * { background: transparent !important; }
  [data-custom-class='title'], [data-custom-class='title'] * { font-family: Arial !important; font-size: 26px !important; color: #000000 !important; }
  [data-custom-class='subtitle'], [data-custom-class='subtitle'] * { font-family: Arial !important; color: #595959 !important; font-size: 14px !important; }
  [data-custom-class='heading_1'], [data-custom-class='heading_1'] * { font-family: Arial !important; font-size: 19px !important; color: #000000 !important; }
  [data-custom-class='heading_2'], [data-custom-class='heading_2'] * { font-family: Arial !important; font-size: 17px !important; color: #000000 !important; }
  [data-custom-class='body_text'], [data-custom-class='body_text'] * { color: #595959 !important; font-size: 14px !important; font-family: Arial !important; }
  [data-custom-class='link'], [data-custom-class='link'] * { color: #3030F1 !important; font-size: 14px !important; font-family: Arial !important; word-break: break-word !important; }
  ul { list-style-type: square; }
  ul > li > ul { list-style-type: circle; }
  ol li { font-family: Arial; }
</style>
<div data-custom-class="body">
<h1 data-custom-class="title">PRIVACY POLICY</h1>
<p data-custom-class="subtitle"><strong>Last updated March 23, 2026</strong></p>

<p data-custom-class="body_text">This Privacy Notice for <strong>Fireside</strong> ("we," "us," or "our") describes how and why we might access, collect, store, use, and/or share ("process") your personal information when you use our services ("Services"), including when you visit our website at <a href="https://bartelme.info" data-custom-class="link">bartelme.info</a>, download and use our application, or engage with us in other related ways.</p>

<p data-custom-class="body_text"><strong>Questions or concerns?</strong> Reading this Privacy Notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services.</p>

<h2 data-custom-class="heading_1">SUMMARY OF KEY POINTS</h2>
<p data-custom-class="body_text"><strong>What personal information do we process?</strong> When you visit, use, or navigate our Services, we may process personal information depending on how you interact with us and the choices you make.</p>
<p data-custom-class="body_text"><strong>Do we process any sensitive personal information?</strong> We may process sensitive personal information (such as religious beliefs) when necessary with your consent or as otherwise permitted by applicable law.</p>
<p data-custom-class="body_text"><strong>Do we collect any information from third parties?</strong> We do not collect any information from third parties.</p>
<p data-custom-class="body_text"><strong>How do we process your information?</strong> We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law.</p>
<p data-custom-class="body_text"><strong>How do we keep your information safe?</strong> We have organizational and technical processes in place to protect your personal information. However, no electronic transmission over the internet can be guaranteed to be 100% secure.</p>
<p data-custom-class="body_text"><strong>What are your rights?</strong> Depending on where you are located, the applicable privacy law may mean you have certain rights regarding your personal information.</p>

<h2 data-custom-class="heading_1">TABLE OF CONTENTS</h2>
<ol data-custom-class="body_text">
  <li><a href="#infocollect">WHAT INFORMATION DO WE COLLECT?</a></li>
  <li><a href="#infouse">HOW DO WE PROCESS YOUR INFORMATION?</a></li>
  <li><a href="#whoshare">WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</a></li>
  <li><a href="#cookies">DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</a></li>
  <li><a href="#ai">DO WE OFFER ARTIFICIAL INTELLIGENCE-BASED PRODUCTS?</a></li>
  <li><a href="#inforetain">HOW LONG DO WE KEEP YOUR INFORMATION?</a></li>
  <li><a href="#infosafe">HOW DO WE KEEP YOUR INFORMATION SAFE?</a></li>
  <li><a href="#infominors">DO WE COLLECT INFORMATION FROM MINORS?</a></li>
  <li><a href="#privacyrights">WHAT ARE YOUR PRIVACY RIGHTS?</a></li>
  <li><a href="#DNT">CONTROLS FOR DO-NOT-TRACK FEATURES</a></li>
  <li><a href="#uslaws">DO UNITED STATES RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</a></li>
  <li><a href="#policyupdates">DO WE MAKE UPDATES TO THIS NOTICE?</a></li>
  <li><a href="#contact">HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</a></li>
  <li><a href="#request">HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</a></li>
</ol>

<h2 id="infocollect" data-custom-class="heading_1">1. WHAT INFORMATION DO WE COLLECT?</h2>
<h3 data-custom-class="heading_2">Personal information you disclose to us</h3>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We collect personal information that you provide to us.</em></p>
<p data-custom-class="body_text">We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.</p>
<p data-custom-class="body_text"><strong>Personal Information Provided by You.</strong> The personal information we collect may include: names, email addresses, and contact preferences.</p>
<p data-custom-class="body_text"><strong>Sensitive Information.</strong> When necessary, with your consent or as otherwise permitted by applicable law, we process the following categories of sensitive information: information revealing religious or philosophical beliefs (e.g., faith background provided during onboarding).</p>
<p data-custom-class="body_text">All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.</p>

<h3 data-custom-class="heading_2">Information automatically collected</h3>
<p data-custom-class="body_text"><em><strong>In Short:</strong> Some information — such as your IP address and browser characteristics — is collected automatically when you visit our Services.</em></p>
<p data-custom-class="body_text">We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, and other technical information.</p>

<h2 id="infouse" data-custom-class="heading_1">2. HOW DO WE PROCESS YOUR INFORMATION?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law.</em></p>
<ul data-custom-class="body_text">
  <li>To facilitate account creation and authentication and otherwise manage user accounts.</li>
  <li>To deliver and facilitate delivery of services to the user.</li>
  <li>To respond to user inquiries and offer support to users.</li>
  <li>To send administrative information to you.</li>
  <li>To send you marketing and promotional communications (you may opt out at any time).</li>
  <li>To evaluate and improve our Services, products, marketing, and your experience.</li>
</ul>

<h2 id="whoshare" data-custom-class="heading_1">3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We may share information in specific situations and with specific third parties.</em></p>
<ul data-custom-class="body_text">
  <li><strong>Business Transfers.</strong> We may share or transfer your information in connection with any merger, sale of company assets, financing, or acquisition of all or a portion of our business.</li>
  <li><strong>Service Providers.</strong> We share data with Supabase (database), Resend (email delivery), OpenAI, and Anthropic (AI processing) under written agreements.</li>
</ul>

<h2 id="cookies" data-custom-class="heading_1">4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We may use cookies and other tracking technologies to collect and store your information.</em></p>
<p data-custom-class="body_text">We use cookies to maintain the security of our Services and your account, prevent crashes, fix bugs, and save your preferences. We do not use cookies for advertising.</p>

<h2 id="ai" data-custom-class="heading_1">5. DO WE OFFER ARTIFICIAL INTELLIGENCE-BASED PRODUCTS?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We offer products, features, or tools powered by artificial intelligence.</em></p>
<p data-custom-class="body_text">As part of our Services, we offer AI-powered journaling prompts and memory enrichment. These tools are powered by Anthropic (Claude) and OpenAI (GPT-4o Mini). Your journal responses are processed by these AI Service Providers to generate personalized prompts and extract themes. Your personal information will be handled in accordance with our agreements with these providers and this Privacy Notice.</p>
<p data-custom-class="body_text"><strong>Important:</strong> Your journal response text is encrypted at rest using AES-256-GCM before storage. Only the minimum necessary content is shared with AI providers to generate your next prompt.</p>

<h2 id="inforetain" data-custom-class="heading_1">6. HOW LONG DO WE KEEP YOUR INFORMATION?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We keep your information for as long as necessary to fulfill the purposes outlined in this Privacy Notice unless otherwise required by law.</em></p>
<p data-custom-class="body_text">We will keep your personal information for as long as you have an account with us. When we have no ongoing legitimate business need to process your personal information, we will delete or anonymize it.</p>

<h2 id="infosafe" data-custom-class="heading_1">7. HOW DO WE KEEP YOUR INFORMATION SAFE?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We aim to protect your personal information through organizational and technical security measures.</em></p>
<p data-custom-class="body_text">We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. Your journal entries are encrypted at the application layer before storage. However, no electronic transmission over the Internet can be guaranteed to be 100% secure. You should only access the Services within a secure environment.</p>

<h2 id="infominors" data-custom-class="heading_1">8. DO WE COLLECT INFORMATION FROM MINORS?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> We do not knowingly collect data from or market to children under 18 years of age.</em></p>
<p data-custom-class="body_text">We do not knowingly collect, solicit data from, or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of a minor and consent to such minor's use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data.</p>

<h2 id="privacyrights" data-custom-class="heading_1">9. WHAT ARE YOUR PRIVACY RIGHTS?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> You may review, change, or terminate your account at any time.</em></p>
<p data-custom-class="body_text"><strong>Withdrawing your consent:</strong> You may withdraw your consent at any time by contacting us using the details in the "HOW CAN YOU CONTACT US" section below.</p>
<p data-custom-class="body_text"><strong>Opting out of marketing:</strong> You can unsubscribe from marketing emails at any time by clicking the unsubscribe link in emails we send or by contacting us directly.</p>
<h3 data-custom-class="heading_2">Account Information</h3>
<p data-custom-class="body_text">You may review or update your account information at any time by logging into your account settings. Upon request to terminate your account, we will deactivate or delete your account and information from our active databases.</p>

<h2 id="DNT" data-custom-class="heading_1">10. CONTROLS FOR DO-NOT-TRACK FEATURES</h2>
<p data-custom-class="body_text">Most web browsers include a Do-Not-Track ("DNT") feature. We do not currently respond to DNT browser signals as no uniform technology standard has been finalized. If a standard is adopted that we must follow, we will inform you in a revised version of this Privacy Notice.</p>

<h2 id="uslaws" data-custom-class="heading_1">11. DO UNITED STATES RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> If you are a US resident, you may have specific rights regarding your personal information.</em></p>
<p data-custom-class="body_text">Depending on your state of residence, you may have the right to: know whether we are processing your personal data; access your personal data; correct inaccuracies; request deletion; obtain a copy of personal data previously shared with us; and opt out of targeted advertising or sale of personal data.</p>
<p data-custom-class="body_text">To exercise these rights, please contact us using the details in section 13 below.</p>

<h2 id="policyupdates" data-custom-class="heading_1">12. DO WE MAKE UPDATES TO THIS NOTICE?</h2>
<p data-custom-class="body_text"><em><strong>In Short:</strong> Yes, we will update this notice as necessary to stay compliant with relevant laws.</em></p>
<p data-custom-class="body_text">We may update this Privacy Notice from time to time. The updated version will be indicated by an updated "Revised" date at the top. We encourage you to review this Privacy Notice frequently.</p>

<h2 id="contact" data-custom-class="heading_1">13. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</h2>
<p data-custom-class="body_text">If you have questions or comments about this notice, you may contact us at:</p>
<p data-custom-class="body_text"><strong>Fireside</strong><br>United States<br>Email: <a href="mailto:privacy@bartelme.info" data-custom-class="link">privacy@bartelme.info</a></p>

<h2 id="request" data-custom-class="heading_1">14. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</h2>
<p data-custom-class="body_text">Based on the applicable laws of your country or state of residence, you may have the right to request access to the personal information we collect from you, correct inaccuracies, or delete your personal information. To request to review, update, or delete your personal information, please contact us at <a href="mailto:privacy@bartelme.info" data-custom-class="link">privacy@bartelme.info</a>.</p>
</div>
`
